### ISSUE TITLE
Question Suggestions!

### ISSUE THREAD

**Issue by RussellDash332** [rish-16/CS3244-Tutorial-Material#1]
**Drop your question(s) here.**
- Shouldn't the first part of the less-preferred alternative in question 3c have [2] as the validation data?
- Is tutorial 5 the same as tutorial 4b?

**What topic(s) is this question from?**
Tutorial 5: Regularization and Validation

**Comment by rish-16** [comment]
Hey Russell, thanks for reaching out!

We're flexible with the less-preferred alternatives actually. As long as the folds aren't comparable, they aren't the best options in our books. So best to stick to something like this:

```
Trg        Val
--------------
[a]        [b]
[b]        [c]
[c]        [d]
```

As for the second question, I'm reorganising the folder structure locally (am yet to push)! Thanks for bringing it up 😃

**Comment by RussellDash332** [comment]
Alright, thanks for clarifying!
